version: '3.9'
services:
  apache:
    image: httpd:latest
    ports:
    - '8080:80'

  app:
    image: python:3.7
    build:
      context: ./docker/python
    volumes:
      - ./src:/src
    environment:
      - TZ=${TZ}
    working_dir: /src
    tty: true
    depends_on:
      - db
    # command: nohup python kishou_data_torikomi/src/main.py & python manage.py runserver 0.0.0.0:8011
    ports: 
      - "18011:8011"

  db:
    container_name: energy_dx_data_platform_db
    user: "1000:50"
    build:
      context: "."
      dockerfile: ./docker/mysql/Dockerfile
    volumes:
      - ./volumes/mysql:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    ports:
      - "33311:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - UPLOAD_LIMIT=100M
      - MAX_EXECUTION_TIME=3600
    ports:
      - "3011:80"
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions
