# Generated by Django 3.2.18 on 2023-04-19 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Houjin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('houjin_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shisetsu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shisetsu_name', models.CharField(max_length=100)),
                ('houjin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy_dx_gui.houjin')),
            ],
        ),
        migrations.AddField(
            model_name='houjin',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy_dx_gui.user'),
        ),
    ]
