# Generated by Django 3.2.18 on 2023-04-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_dx_gui', '0002_rename_user_id_houjin_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='houjin',
            table='t_houjin',
        ),
        migrations.AlterModelTable(
            name='shisetsu',
            table='t_shisetsu',
        ),
    ]
