# Generated by Django 3.2.18 on 2023-04-24 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_dx_gui', '0003_auto_20230421_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shisetsu',
            old_name='houjin_id',
            new_name='houjin',
        ),
        migrations.AlterModelTable(
            name='user',
            table='t_users',
        ),
    ]
